name: Helm CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - "myapp/values.yaml"

jobs:
  deploy:
    runs-on: ubuntu-latest 
    # Добавляем переменную окружения для принудительного использования Node.js 24
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout repo
        # Обновляем версию действия до последней (если доступна v5 или выше)
        uses: actions/checkout@v5  # замените на актуальную версию, проверьте на GitHub Marketplace

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s \
          https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Setup kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      - name: Helm upgrade
        run: |
          helm upgrade myapp ./myapp
