ame: Helm CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - "myapp/values.yaml"

jobs:
  deploy:
    runs-on: self-hosted  # Изменено с ubuntu-latest на self-hosted
    # Добавляем переменную окружения для принудительного использования Node.js 24
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout repo
        # Обновляем версию действия до последней (если доступна v5 или выше)
        uses: actions/checkout@v5  # замените на актуальную версию, проверьте на GitHub Marketplace

      - name: Setup kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      - name: Helm upgrade
        run: |
          helm upgrade myapp ./myapp
